name: Lint

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm_version: [3.2.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '${{ matrix.helm_version }}'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --charts . --validate-maintainers=false --lint-conf=lintconf.yaml
